
MOVE_AHEAD = 'MoveAhead'
ROTATE_LEFT = 'RotateLeft'
ROTATE_RIGHT = 'RotateRight'
LOOK_UP = 'LookUp'
LOOK_DOWN = 'LookDown'
SEEN_BOWL = 'SeenBowl'
SEEN_TOMATO = 'SeenTomato'

BASIC_ACTIONS = [MOVE_AHEAD, ROTATE_LEFT, ROTATE_RIGHT, LOOK_UP, LOOK_DOWN, SEEN_BOWL, SEEN_TOMATO]

GOAL_SUCCESS_REWARD = 2.5
INTERMED_FIND_REWARD = 2.5
STEP_PENALTY = -0.01
